### ISSUE TITLE
Cannot select the correct device

### ISSUE THREAD

**Issue by zeridon** [G4PLS/AudioControl#6] opened 2024-09-16 08:49 UTC
Currently I am unable to select the right device i have for control.

hardware present: `00:1f.3 Audio device: Intel Corporation Raptor Lake-P/U/H cAVS (rev 01)`
pacmd list-sinks: attached [pacmd-list-sinks.txt](https://github.com/user-attachments/files/17010438/pacmd-list-sinks.txt)

What i see:
 * list of 4 identically named sinks (screenshot attached) [sinks-the-same](https://github.com/user-attachments/assets/674a3ced-c6aa-4a75-82ad-79da87e14aea)
 * No matter which i select it uses the first one (which is wrong for me)

What is expected: Being able to select device to control and seeing better names.

**Comment by zeridon** [comment] 2024-09-16 08:52
I can fix this (at least for my use case) by removing all alsa related properties from https://github.com/G4PLS/AudioControl/blob/5352683ec6e4fad56725142792509aa646d7e6ae/actions/DeviceBase.py#L256 or by adding on top `"alsa.id"`

**Comment by G4PLS** [comment] 2024-09-16 17:33
Ohh i see where the problem is
I updated my plugin but never pushed it to the store

I will create a store PR when I have time, this should probably fix that

**Comment by G4PLS** [comment] 2024-11-01 13:55
Sorry that its been that long, within the next 1-2 weeks I will roll out a "bigger" update of the Plugin, in there the new naming should be included

Issue will be kept open until the next release

**Comment by G4PLS** [comment] 2024-11-07 19:35
New Naming is added, just need to wait until StreamController implements a fix that is needed for the Action to load

**Comment by G4PLS** [comment] 2024-11-22 20:16
With the latest version this should now have been improved
With this I will close the issue, if there is anything else a new issue will need to be opened

**Closed by G4PLS** 2024-11-22 20:16 UTC
